### ISSUE TITLE
tslint keeps yelling

### ISSUE THREAD

**Issue by kushalmahajan** [facebookincubator/redux-react-hook#11]
Usage 
```import { useMappedState } from "redux-react-hook";```

Error - `[ts] Cannot find module 'redux-react-hook'.`

Tried removing node_modules and yarn install too but to no avail.

**Comment by yyynnn** [comment]
Did you check your `package.json` for eg `redux-react-hook": "^2.0.0",` ?

**Comment by kushalmahajan** [comment]
Ha-ha. Yes, it's there.

**Comment by ianobermiller** [comment]
Is that TSLint or just TypeScript? I created a new project from scratch using create-react-app and using TypeScript, Redux, and this hook, and it worked fine. Closing as not repro, but please feel free to share your repository and we can take a look.
