### ISSUE TITLE
Equivalent for mapStateToProps's `ownProps`

### ISSUE THREAD

**Issue by Federkun** [facebookincubator/redux-react-hook#14]
This evening I was playing with this api, and I got myself in the need of using some props of my functional component to fetch some state.

The problem: 

```
import { useMappedState } from 'redux-react-hook'

const mapState = (state) => ({
  selectedProfile: state.profiles[somePropsHere] // how do I pass` somePropsHere`?
})

export default ({ somePropsHere }) => {
  const { selectedProfile } = useMappedState(mapState)

```

I come out with a quick solution:

```
import { useCallback } from 'react'
import { useMappedState as useReduxMappedState } from 'redux-react-hook'

export function useMappedState(mapState, additionalProps) {
  const wrappedMapState = useCallback((state) => mapState(state, additionalProps), [])
  return useReduxMappedState(wrappedMapState)
}
```

Which allow you to forward props from the component to the map state callback:

```
const mapState = (state, { somePropsHere }) => ({
  selectedProfile: someSelectorThatUseProps(somePropsHere, state),
})

export default ({ somePropsHere }) => {
  const { selectedProfile } = useMappedState(mapState, { somePropsHere })
```

Since this is a replacement for react-redux, is it worth to send a PR to allow this kind of behaviour? Or is there a better alternative?

**Comment by ianobermiller** [comment]
Curious as to why you closed the issue. To answer your question, you should use `useCallback` with a dependencies array, as in [the documentation for `useMappedState`](https://github.com/facebookincubator/redux-react-hook#usemappedstatemapstate).

**Comment by Federkun** [comment]
Yeah, that's what I realised after waking up the next morning; sorry about that.

**Comment by ianobermiller** [comment]
No problem at all, I'd rather have you ask than wonder!
