### ISSUE TITLE
Unsubscribed listeners might get notified

### ISSUE THREAD

**Issue by Turanchoks** [facebookincubator/redux-react-hook#17]
I came up with the exact same implementation of a hook for Redux and faced a problem that a redux listener is notified after it has unsubscribed.

The way I found it:
There is timer ticking every second and dispatching Date.now() to the store. And there are two components both subscribed to the store. One gets a timestamp from the store, the other gets derived data using a memoized (useCallback) selector which depends on a prop. If the prop changes the selector is recreated causing the listener bound to the previous selector to unsubscribe. However sometimes a listener is notified with a new state after it's unsubscribed. It happens because an ensureCanMutateNextListeners function in redux creates a temporary array of listeners while dispatching which may cause a wrong behaviour.

It's easier to demonstrate this with an example. In the example below there is also a very naive redux implementation. You can use it to see what's causing the problem.
https://codesandbox.io/s/3q0j74m0lq

Below is code from redux-react-hook showing the useEffect that causes a problem. One solution to the problem is to use useLayoutEffect so the re-subscription is scheduled right after the render.
```js
useEffect(
  () => {
    let unsubbed = false;
    const checkForUpdates = () => {
      if (unsubbed) {
        // this shouldn't be reachable
      }

      const newDerivedState = runMapState();
      if (!shallowEqual(newDerivedState, lastRenderedDerivedState.current)) {
        setDerivedState(newDerivedState);
      }
    };
    checkForUpdates();
    const unsubscribe = store.subscribe(checkForUpdates);
    return () => {
      unsubscribe();
      unsubbed = true;
    };
  },
  [store, mapState]
);
```

I've spent quite some time figuring out how it should or should not work and I'm willing to help.

**Comment by takion** [comment]
I found that you can also solve this issue by changing redux-react-hook core like this:

from this
```js
if (!shallowEqual(newDerivedState, lastRenderedDerivedState.current)) {
  setDerivedState(newDerivedState)
}
```

 to this

```js
if (!shallowEqual(newDerivedState, lastRenderedDerivedState.current)) {
  setImmediate(()=>{
    setDerivedState(newDerivedState)
  })
}
```

like in easy-peasy https://github.com/ctrlplusb/easy-peasy/blob/master/src/hooks.js

**Comment by ianobermiller** [comment]
@Turanchoks thanks for the detailed report! Would you be up for adding a test and a fix in a new PR? I'm also interested in @takion's fix, and I've reached out to the Reac team to get their perspective.

**Comment by Turanchoks** [comment]
@ianobermiller Sure, but I'm still not sure what's the best solution here

**Comment by ianobermiller** [comment]
I agree that we don’t know the correct fix. I’m experiencing this same bug on our app as well. I figured the PR would be a place to experiment, and if we can reproduce this in a test case that’d be ideal. Is it possible that this is a bug in Redux?

**Comment by Turanchoks** [comment]
I don't think so. It seems like that's how hooks work. When using useEffect the way we do to subscribe to Redux, re-subscription occurs while a listener is being invoked so that in the render phase we get outdated data. So it has nothing to do with ensureCanMutateNextListeners. I'm sorry.  In the example code I provided disabling ensureCanMutateNextListeners helped because there were 2 listeners. However the behaviour is reproducible with just a single listener.

I've attached an id to a listener and here is what happens. useLayoutEffect indeed re-subscribes before notifying. Wrapping setDerivedState in setTimeout also works but it looks kinda weird and I would like to test it better.

useEffect | useLayoutEffect|setTimeout around setDerivedState
--------- | ----------------|------------------------------------
Renders: 1 | Renders: 1|Renders: 1
Did subscribe to 1|Did subscribe to 1|Did subscribe to 1
Renders: 2|Renders: 2|Renders: 2
Renders: 3|Renders: 3|Renders: 3
**Will notify 1**|**Did unsubscribe from 1**|**Will notify 1**
**Did unsubscribe from 1**|**Did subscribe to 2**|**Did notify 1**
Did subscribe to 2|Renders: 4|**Did unsubscribe from 1**
Renders: 4|**Will notify 2**|**Did subscribe to 2**
Renders: 5|Renders: 5|Renders: 4
**Did notify 1**|**Did notify 2**|Renders: 5

**Comment by Turanchoks** [comment]
@gaearon I'm sorry I've changed codesandbox and it wasn't accurate. Now it works as expected.

Originally I thought that this problem might have something to do with ensureMutateListeners that copies listeners before every dispatch. That's why on the example codesanbox there is a custom createStore implementation with it's own ensureMutateListeners. But it does not. 

I understand why we might end up in a listener that has been unsubscribed. It's exactly what happens in the table I commented earlier in `useEffect` column. But probably  this shouldn't happen when using this library correctly as it may result in an outdated update.

**Comment by Turanchoks** [comment]
Sure. Here it is: https://codesandbox.io/s/10pyxnm454

**Comment by gaearon** [comment]
There's a few mistakes I think I see in this implementation:

1. By the time `useEffect` runs store state might have changed. So it's not enough to just call `subscribe` in `useEffect`. You need to also check for updates.

2. As mentioned in https://github.com/facebookincubator/redux-react-hook/issues/17#issuecomment-459497681, unsubscribing in Redux *doesn't* guarantee the old listener won’t run during dispatch. So in each `handleChange` you need to explicitly track whether a listener is stale or not.

So this version seems like it would work?

https://codesandbox.io/s/koool4oxo3

```js
  useEffect(
    () => {
      let didUnsubscribe = false;
      const checkUpdates = () => {
        if (didUnsubscribe) {
          // Don't run stale listeners
          return;
        }
        const nextMappedState = getMappedState();
        if (
          prevMappedState.current !==
          nextMappedState
        ) {
          setMappedState(nextMappedState);
        }
      };
      checkUpdates();
      let unsubscribe = store.subscribe(
        checkUpdates
      );
      return () => {
        didUnsubscribe = true;
        unsubscribe();
      };
    },
    [store, selector]
  );
```

**Comment by gaearon** [comment]
I sent https://github.com/facebookincubator/redux-react-hook/pull/22 as a possible fix.
