### ISSUE TITLE
UseMappedState firing continuously and re-rendering the component

### ISSUE THREAD

**Issue by kushalmahajan** [facebookincubator/redux-react-hook#18]
Since the question statement makes it clear about problem statement, I'll jump right to code

```
const MyComponent = ({}) => {

    const mapState = useCallback(state => state.salesPerfReducer.salesPerf, []);
    const salesPerfData = useMappedState(mapState);
    console.log('component rendering...')
    // My custom hooks ( Nothing wrong here ...)
    const [tabIndex, handleTabChange] = useTab(0);
    const [duration, handleDurationChange] = useDuration('last3');
    
    const dispatch = useDispatch();
    useEffect( () => {
        console.log('fired')
        dispatch(fetchSalesPerf({ filter: 'monthly', duration: 'last3' })); // This is an API call and uses redux-observable for handling that async part
    }, [tabIndex, duration]);
   
    return (
        <section>
            Component
        </section>
    )
}
```

I see that my console.log is updating continuously. 

When I tried commenting 

```
 const mapState = useCallback(state => state.salesPerfReducer.salesPerf, []);
 const salesPerfData = useMappedState(mapState);
```

it only logs once. i.e. this statement ` console.log('component rendering...')` is fired once.

So I'm using `[]` for `useCallback` which will fire every time as no dependencies are specified. But I'm not sure what to pass in as dependencies here. I tried `[tabIndex, duration]` but it was same.

First, checking this dependency could be built-in to useMappedState. Otherwise one would have to manually specify. 

Taking this example, I don't want to run my API again unless my api Data is changed.  Should be implicit.

Even if not for now. What's the way to make it know about that.  I see in docs's example that you use a prop `index` in your component to pass to useCallback. But how can I prevent this here?

**Comment by kushalmahajan** [comment]
It's useEffect firing despite the dependency array. Closing the issue therefore from redux-react-hook repo

**Comment by Turanchoks** [comment]
You can just extract the selector function outside of the component so it is never recreated. You should use useCallback to create a selector if it depends on the props, for example, then they would be dependencies for useCallback hook.

Your code seems valid to me. There might be something wrong with useTab, useDuration or action handling. Or maybe you render it more than once on the page. 😃

**Comment by ianobermiller** [comment]
Can you please provide a codesandbox with a working repro?

**Comment by kushalmahajan** [comment]
It was one of action type string mismatch 😪
