### ISSUE TITLE
dispatch firing multiple times inside useEffect hook

### ISSUE THREAD

**Issue by kushalmahajan** [facebookincubator/redux-react-hook#19]
Say I have to use dispatch inside `useEffect` on initial render and then whenever my two state values  changes which are basically user action based ( Equivalent of cDM and cDU) and I code it like this

```
useEffect(
        () => {
            dispatch(fetchSalesPerf({ filter: 'monthly', duration: 'last3' }))
        },
        [tabIndex, duration ]
    );
```

Shouldn't this be a single dispatch call firing a single network request? 

What I see is that I have multiple API calls for same endpoint flooding my network tab. 

I don't have any setInterval in my action creators or epics. But still they go on. 

Any way to mitigate this.  I'm linking an issue which is related to this. However, I know that source of trouble is dispatch and not useMappedState. What are your thoughts ? 

#18

**Comment by ianobermiller** [comment]
Can you please provide a codesandbox with a working repro?

**Comment by kushalmahajan** [comment]
It was one of action type string mismatch 😪

**Comment by Renathesco** [comment]
Qual a solução? Não entendi as soluções acima
