### ISSUE TITLE
What about single selector subscription?

### ISSUE THREAD

**Issue by Voronar** [facebookincubator/redux-react-hook#29]
What about [single selector subscription](https://github.com/gostgroup/use-redux#usereduxstateselectorstateselector-state-t--r-r) like [this one](https://github.com/gostgroup/use-redux/blob/master/src/useReduxStateSelector.ts)?

**Comment by Turanchoks** [comment]
In the code you linked useEffect callback is only invoked on initial render so if a new selector is provided it will never be used.

**Comment by ianobermiller** [comment]
Yeah that looks very similar, just without the shallow equal check. Is there an actionable request here? You could change this issue to be about allowing a custom comparison function. If you do, please reopen.
