### ISSUE TITLE
Use react-redux Context

### ISSUE THREAD

**Issue by Cretezy** [facebookincubator/redux-react-hook#3]
Instead of having our own provider (`StoreProvider`), we could just use Redux 0.6's `ReactReduxContext`.

https://github.com/reduxjs/react-redux/blob/dba598bef291793aff2afa73355d0b3a00489bb0/src/index.js#L3

This could simplify the code, and avoid having 2 providers

**Comment by ianobermiller** [comment]
`redux-react-hook` is meant to be a replacement for React Redux, though, so it wouldn't make sense to take a dependency on that library. 

Fun fact: I specifically named this `redux-react-hook` as opposed to `react-redux-hook` for this reason :)

**Comment by langpavel** [comment]
@ianobermiller Yeah, completely understood. But what about seamless gradual upgrade?
There should be a way how to inject context from `react-redux`
