### ISSUE TITLE
useMappedState should have selectors as dependencies

### ISSUE THREAD

**Issue by otakustay** [facebookincubator/redux-react-hook#41]
When state is mapped to an object or array like:

```js
const getUsers = useCallback(
    state => {
        const ids = state.userIds;
        return ids.map(id => state.userStore[id]);
    },
    []
);
const users = useMappedState(getUsers);
```

The returning `users` can be a new array instance each time this component renders, passing `users` to a sub component could cause a re-render even `userIds` and `userStore` are not modified.

I'd rather to provide a more [reselect](https://github.com/reduxjs/reselect) like API:

```js
const getUsers = useCallback(
    (ids, userStore) => ids.map(id => userStore[id]),
    []
);
const users = useMappedState(
    getUsers,
    [state => state.userIds, state => state.userStore]
);
```

In which the values returned by the second argument become dependencies to a `useMemo` call.

**Comment by ianobermiller** [comment]
I don't want to expand the scope of `redux-react-hook` to include selectors. Especially since not everyone uses the same selector library or the same configurations of reselect for that matter. This would be a perfect use case for a custom hook.
