### ISSUE TITLE
ReactDOM peer dependency

### ISSUE THREAD

**Issue by tom-drake** [facebookincubator/redux-react-hook#42]
Does ReactDOM need to be a peer dependency for this? I can only see it being used in a test file. I've been using this library in a react-native app and so far it has been fine apart from the `npm install` console warning which I just ignore for now.

**Comment by ianobermiller** [comment]
Good catch, probably not. Would you like to send a PR?

**Comment by ianobermiller** [comment]
Fixed in 7d6dfb770c99a3df8f76cdc2800f31d3ae55ba5e and published as v3.2.1

**Comment by tom-drake** [comment]
Thanks for getting that sorted. I would have got a PR in but have been a little busy :(

**Comment by ianobermiller** [comment]
No problem, it had been a while since I touched the project, too.
