### ISSUE TITLE
Hooks can only be called inside the body of a function component.

### ISSUE THREAD

**Issue by lichspace** [facebookincubator/redux-react-hook#43]
include  react with
```
<script src="/js/lib/react.production.min.js"></script>
<script src="/js/lib/react-dom.production.min.js"></script>
```

include redux-react-hook with webpack
`import {StoreContext,useMappedState,useDispatch} from 'redux-react-hook';
`

> Error:Hooks can only be called inside the body of a function component.

i find _node_modules/redux-react-hook/dist/index.js_ has code

`var react = require('react');
`
i think this cause the error

I resolve this with：copy redux-react-hook/dist/index.js to my project and modify

`var react = React;//from window.React
`

so, i want ask has a better way?

**Comment by ianobermiller** [comment]
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

You likely have two copies of React, the one you are including manually and the one packaged by webpack. You can remove the script tags.
