### ISSUE TITLE
How to use this with NextJS?

### ISSUE THREAD

**Issue by sandervspl** [facebookincubator/redux-react-hook#46]
I'm trying to get this library to work on my NextJS project, but so far it's not working. I have set up Redux exactly like the [NextJS example](https://github.com/zeit/next.js/tree/master/examples/with-redux), for reference. That implementation works fine.

This is my `_app.tsx` component
```jsx
<Container>
  <StoreContext.Provider value={reduxStore}>
    <Component {...pageProps} />
  </StoreContext.Provider>
</Container>
```

The error that I get is
`redux-react-hook requires your Redux store to be passed through context via the <StoreContext.Provider>`

Did anyone get this to work with NextJS yet? Or does anyone have an idea how it might work with NextJS / SSR?

**Comment by ianobermiller** [comment]
Can you provide a CodeSandbox with a repro? Is it possible you are creating two different `StoreContext` instances? Closing because this is likely a configuration issue, but I'll continue to respond.

**Comment by sandervspl** [comment]
I recreated the problem in the following codesandbox https://codesandbox.io/s/k901x91nzv
I followed the NextJS Redux example for it.

**Comment by thomasdola** [comment]
any update on this issue?
getting the same error...

**Comment by ianobermiller** [comment]
I'm not seeing any error when running that codesandbox -- `{isLoading: false}` is correctly logged to the console.
