### ISSUE TITLE
Seamless gradual upgrade from react-redux

### ISSUE THREAD

**Issue by langpavel** [facebookincubator/redux-react-hook#47]
Related to #3 

**Edit:** This will not work because `react-redux` injects *state* but `redux-react-hooks` injects *store* into Context

~~If `redux` is same, then reusing context should be as easy as injecting foreign context object:~~

https://github.com/facebookincubator/redux-react-hook/blob/3a86bc02ca81def12e0240c986d56ee1da5fc792/src/create.ts#L21-L30

<details>
 <summary>new code (will not work)</summary>

```ts
export function create< 
  TState, 
  TAction extends Action, 
  TStore extends Store<TState, TAction> 
>(customContext?: React.ContextType): { 
  StoreContext: React.Context<TStore | null>; 
  useMappedState: <TResult>(mapState: (state: TState) => TResult) => TResult; 
  useDispatch: () => Dispatch<TAction>; 
} { 
  const StoreContext = customContext || createContext<TStore | null>(null); 

  // ...
}
```

</details>

This may break if context shapes from `react-redux` and `redux-react-hook` are different — **they *are* different**

**Comment by ianobermiller** [comment]
In our app we made a `StoreContext.react.js` component that applies both the `react-redux` provider and the `redux-react-hook` provider, and just use that everywhere. As you pointed out, the shapes are not the same, so this won't really work.
