### ISSUE TITLE
How to make this works with ConnectedRouter ?

### ISSUE THREAD

**Issue by kunyan** [facebookincubator/redux-react-hook#51]
The ConnectedRouter require a `<Provider>` in the root,
However, the redux-react-hook is using context to replace it.

I have try to use 
```
<StoreContext.Provider value={store}>
    <Provider store={store}>
      <ConnectedRouter history={browserHistory}>
        <Switch>
          ...
        </Switch>
      </ConnectedRouter>
    </Provider>
  </StoreContext.Provider>

```

But looks not works perfectly

**Comment by ianobermiller** [comment]
Can you provide a codesandbox with a repro? You will need to use the react-redux Provider if you want to use ConnectedRouter. Otherwise, you will have to look for another solution, see #49.
