### ISSUE TITLE
Reducing components rerenders

### ISSUE THREAD

**Issue by goloveychuk** [facebookincubator/redux-react-hook#53]
Looks like we can reduce component rerenders count by removing `useEffect` from here
https://github.com/facebookincubator/redux-react-hook/blob/676a270be12f0bcbffe9d650ef769d6dd486ef70/src/create.ts#L91-L94
Since `useEffect` will execute somewhen in the future after component renders, even if our hook already returned new state, 
https://github.com/facebookincubator/redux-react-hook/blob/676a270be12f0bcbffe9d650ef769d6dd486ef70/src/create.ts#L110
still compares to old. 

In practice, for my case, with using 6 hooks and 4 dispatches, it's reducing rerenders counts from 6 to 4.

here is used useLayoutEffect
https://github.com/reduxjs/react-redux/blob/06a674e733454b08bb4090f8bcb038a3a003e6aa/src/hooks/useSelector.js#L79-L85
Which seems to work correctly too.

**Comment by goloveychuk** [comment]
In practice, for my case, with using 6 hooks, it's reducing rerenders counts from 6 to 4.

**Comment by markerikson** [comment]
The original implementation `connect` in v7.0 used `useEffect(), but we ran into issues with the timing of subscriptions, so we had to change that to `useLayoutEffect()` as well:

https://github.com/reduxjs/react-redux/issues/1226
https://github.com/reduxjs/react-redux/pull/1235

**Comment by arwysyah** [comment]
const Home = ({navigation}) => {
  const globalState = useSelector(state=>state)
  
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const dispatch = useDispatch()
  useLayoutEffect(()=>{
    dispatch(watchData())
  },[dispatch])

  useLayoutEffect(() => {
    setTimeout(() => {
      setData(data);
     
      setLoading(false);
    }, 1000);
  }, [data]);
console.log(globalState.request)
return()}



this functional component rander three times when i dispatch a action with redux, can anyone tell me whats wrong with this one ?

**Comment by ianobermiller** [comment]
@arwysyah A codesandbox link would make your problem easier to diagnose, as the code doesn't seem to make sense on its own.
