### ISSUE TITLE
use useEffect instead of useLayoutEffect

### ISSUE THREAD

**Issue by istarkov** [facebookincubator/redux-react-hook#55]
Setting here https://github.com/facebookincubator/redux-react-hook/blob/e8830371ec22fe171a98f1b537a7a3f8e8ef0af3/src/create.ts#L115  `useEffect` instead of `useIsomorphic...` gives zero failing tests, even test provided for `useLayoutEffect` change works fine. 
From what I see there is no real need of using useLayoutEffect in that place or any real test needed.

**Comment by ianobermiller** [comment]
@goloveychuk Can you please take a look? It seems like the tests would have passed without the product changes.

**Comment by goloveychuk** [comment]
I have 
```
● redux-react-hook › useMappedState › renders once if have multiple useMappedState

    expect(received).toBe(expected) // Object.is equality

    Expected: 3
    Received: 5

      286 |       updateStoreWithoutAct({bar: 12, foo: '12'});
      287 |       act(() => {});
    > 288 |       expect(renderCount).toBe(3);
          |                           ^
      289 |     });
      290 |
      291 |     it('throws if provider is missing', () => {

      at Object.toBe (src/__tests__/index-test.tsx:288:27)
```
when use `useEffect`

**Comment by istarkov** [comment]
Try clean install as I have zero errors on master
![image](https://user-images.githubusercontent.com/5077042/57975379-4b009a80-79d0-11e9-856e-c1449344a3d7.png)
with  `useEffect(() => {` setted here https://github.com/facebookincubator/redux-react-hook/blob/master/src/create.ts#L115

Just console errors `Warning: An update to Component inside a test was not wrapped in act(...).`

**Comment by istarkov** [comment]
PS: Your error is only shown if both effects changed on `useEffect`, but only last must be changed

**Comment by goloveychuk** [comment]
Yea, we can use “useEffect” in subscribe function.

**Comment by ianobermiller** [comment]
@istarkov Would you like to send a PR?

**Comment by ianobermiller** [comment]
@goloveychuk are you up for fixing this?

**Comment by ianobermiller** [comment]
So I wrote some tests that don't work if you `useEffect`, so I think it is wise to keep `useLayoutEffect` for now.
