### ISSUE TITLE
Flow error: Redundant argument. This argument doesn't change any lint settings.

### ISSUE THREAD

**Issue by osmestad** [facebookincubator/redux-react-hook#57]
When trying to upgrade to latest version of this library (`3.3.2` from `3.2.1`) I get Flow failures for both the usages of:
`// flowlint-next-line unclear-type: off` in`dist/index.js.flow`
The error is:
`Redundant argument. This argument doesn't change any lint settings.`
Happens when using Flow `0.100.0`

**Comment by ianobermiller** [comment]
You can fix this by adding the following to your `.flowconfig`:

```
[strict]
unclear-type
```

At Facebook, ours looks like this:
```
[strict]
deprecated-type
nonstrict-import
sketchy-null
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import
```

Read more about `@flow strict` and `@flow strict-local` here: https://flow.org/en/docs/strict/.

If it would help, I can add these changes just locally in the FB codebase and remove them from the public definitions. What do you think?

**Comment by osmestad** [comment]
Thanks!
Adding a `[strict]` block to our `.flowconfig` solves it for us. 
I think this should probably be considered a bug in Flow though, as I think it should not report this error for library dependencies? So maybe we should open an issue there? (I did not find any similar issue there)

**Comment by osmestad** [comment]
In theory I thought it should be possible to avoid the error by having a section like this in  `.flowconfig`:
```
[declarations]
.*/node_modules/.*
```
But that does not seem to work for me.
