### ISSUE TITLE
question about re-render guarantee mentioned in docs

### ISSUE THREAD

**Issue by kushalmahajan** [facebookincubator/redux-react-hook#58]
> React Redux also guarantees that data flows top down, so that child components update after their parents, which the hook does not.

What does it means it doesn't flows top down.  re-renders work fine for children. In which cases this guarantees is broken?

**Comment by ianobermiller** [comment]
The React Redux docs cover this quite well: https://react-redux.js.org/next/api/hooks#stale-props-and-zombie-children
