### ISSUE TITLE
sometime async dispatch will not update by finally

### ISSUE THREAD

**Issue by xiaoTuiMao** [facebookincubator/redux-react-hook#59]
```javascript
const Loading = () => {
  const { requestCount } = useMappedState(state => state.framework);
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(actions.addRequestCount());
    setTimeout(() => {
      dispatch(actions.subRequestCount());
    }, 10);
  }, []);
  return (
    <div className={cx(styles.container, { [styles.showLoading]: requestCount > 0 })}>
      <img src={loadingIcon} alt="loading" />
    </div>
  );
};
```

and console in 
![image](https://user-images.githubusercontent.com/15075094/59759724-45de8600-92c3-11e9-9bef-ffd304350531.png)

work success console
![image](https://user-images.githubusercontent.com/15075094/59759543-e97b6680-92c2-11e9-9990-60f7655ceffd.png)

work fail console
![image](https://user-images.githubusercontent.com/15075094/59759613-13348d80-92c3-11e9-97af-ef8f225b186e.png)

**Comment by ianobermiller** [comment]
May you please provide a code pen with a full reproduction? There is too much going on in your example to know what the problem is.

**Comment by xiaoTuiMao** [comment]
thanks for your reply. i had try again, but I can't reproduce this bug now.
