### ISSUE TITLE
mapState function cannot return a function ?

### ISSUE THREAD

**Issue by xinkule** [facebookincubator/redux-react-hook#60]
When I'm using reselect along with redux-react-hook, there is a situation that needs the mapStateToProps function (mapState function in redux-react-hook) to return a function, but it seems this lib hasn't supported it yet ?

![屏幕快照 2019-07-09 11 42 08](https://user-images.githubusercontent.com/10016218/60857883-cea36e80-a23e-11e9-8c01-bea32b95c812.png)

**Comment by ianobermiller** [comment]
This would be a good one to add to the docs. Basically, you need to create the selector with `useMemo`, so it has the same reference for the lifetime of the component:

```tsx
function MyComponent() {
  const getVisibleTodos = useMemo(() => makeGetVisibleTodos(), []);
  const {todos} = useMappedState(useCallback(state => getVisibleTodos(state,  props)), [props]));
}
```

**Comment by xinkule** [comment]
> This would be a good one to add to the docs. Basically, you need to create the selector with `useMemo`, so it has the same reference for the lifetime of the component:
> 
> ```tsx
> function MyComponent() {
>   const getVisibleTodos = useMemo(() => makeGetVisibleTodos(), []);
>   const {todos} = useMappedState(useCallback(state => getVisibleTodos(state,  props)), [props]));
> }
> ```

Thanks for the tips, I almost forgot the `useMemo` api. Maybe I could just use `useMemo` to replace the selector if I don't need to reuse ?

**Comment by xinkule** [comment]
@ianobermiller And I think `getVisibleTodos` function should be in the dependency list of `useCallback` hook in the doc ?

**Comment by ianobermiller** [comment]
Yup, you are right. Can you send a PR please?
