### ISSUE TITLE
crazy thought: useDispatch() returns wrapper that invokes dispatch() on Redux store as well as any number of React.useReducer() state mutators

### ISSUE THREAD

**Issue by warren-bank** [facebookincubator/redux-react-hook#78]
I don't know if this would be considered an anti-pattern.

Redux seems like the right place to store state that needs to be shared with other React components. But if for some reason an app chooses to store some bit of state in a React component and then needs to pass callbacks to children, it is likely to follow the [recommend convention](https://reactjs.org/docs/hooks-faq.html#how-to-avoid-passing-callbacks-down) to pass down a `dispatch` function from [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer) via `context`.

In this scenario, it would be convenient to be able to merge Redux and React `dispatch` functions.

pseudo code:

```javascript
import {useReducer} from 'react';
import {useDispatch} from 'redux-react-hook';

function todosReducer(todosState, action) {
  switch (action.type) {
    case 'ADD_TODO':
      return [...todosState, action.payload];
    default:
      return todosState;
  }
}

function TodosApp() {
  const [dispatch, addDispatcher] = useDispatch();  // could omit `dispatch` from destructured Array
  const [todos, todosDispatcher] = useReducer(todosReducer, []);
  addDispatcher(todosDispatcher);

  return (<DeepTree todos={todos} />);
}
```

```javascript
import {useDispatch} from 'redux-react-hook';

function DeepChild(props) {
  const [dispatch, addDispatcher] = useDispatch();  // could omit `addDispatcher` from destructured Array

  function handleClick() {
    dispatch({ type: 'ADD_TODO', payload: 'buy milk' });
  }

  return (
    <button onClick={handleClick}>Add todo</button>
  );
}
```

- - - -

implementation could be as simple as:

in file [`create.ts`](https://github.com/facebookincubator/redux-react-hook/blob/5008c2f72405eee374074888d482c9b8a2603893/src/create.ts#L160):

change from:

```javascript
  function useDispatch(): Dispatch<TAction> {
    const store = useContext(StoreContext);
    if (!store) {
      throw new MissingProviderError();
    }
    return store.dispatch;
  }
```

to:

```javascript
  const reactDispatchers = [];

  const addDispatcher = (dispatch) => reactDispatchers.push(dispatch);

  function useDispatch(): Dispatch<TAction> {
    const store = useContext(StoreContext);
    if (!store) {
      throw new MissingProviderError();
    }

    const combinedDispatcher = (action) => {
      ;[...reactDispatchers, store.dispatch].forEach(dispatch => dispatch(action))
    }

    return [combinedDispatcher, addDispatcher];
  }
```

**Comment by warren-bank** [comment]
Of course, you probably wouldn't want to break your API..

in that case:
* `addDispatcher` could be its own export
* `useDispatch` could only return `combinedDispatcher`

**Comment by ianobermiller** [comment]
I think this is a bit too specific to include in this generic library, and it is also a bit more complicated than presented. Importantly, the added dispatch should only be available to child components (not globally) and you need a way to remove the added dispatch when the parent component unmounts. Since you can't add a context provider with hooks,, I think the only way to do this would be by using a special wrapper component (with a context provider):

```tsx
function TodosApp() {
  const dispatch = useDispatch();  // could omit `dispatch` from destructured Array
  const [todos, todosDispatcher] = useReducer(todosReducer, []);

  return (
    <CombineDispatches dispatches=([dispatch, todosDispatcher]}>
      <DeepTree todos={todos} />
    </CombineDispatches>
  );
}

function DeepChild(props) {
  const dispatch = useCombinedDispatch(); // Could fallback to redux-react-hooks dispatch

  function handleClick() {
    dispatch({ type: 'ADD_TODO', payload: 'buy milk' });
  }

  return (
    <button onClick={handleClick}>Add todo</button>
  );
}
```

If you'd like to release such a library, I'd be happy to promote it in the docs!

**Comment by warren-bank** [comment]
I whipped up a [little library](https://github.com/warren-bank/react-custom-hooks/tree/master/packages/unified-redux-react-hook) to [demo](https://warren-bank.github.io/react-custom-hooks/packages/unified-redux-react-hook/demos/01%20-%20demo%20-%20redux%20state%20todos%20-%20react%20state%20theme.html) what I had in mind.

It feels like a monkey patch for 'redux-react-hook', but I suppose I should dress that up a bit and say that I used [composition](https://reactjs.org/docs/composition-vs-inheritance.html) :)

I still need to write up a few unit tests and make sure that the React dispatch functions are removed when their corresponding components unmount. When added by `useDispatch(...dispatchers)`, `React.useEffect` is used to add them to an array, which returns a cleanup function to remove them as well. That _should_ be sufficient to avoid memory leaks.

**Comment by ianobermiller** [comment]
pretty neat. 

> any action passed to this function will be forwarded to **all** registered React dispatch function(s)

This is problematic, as it breaks encapsulation and makes it possible for components to be coupled solely via the global state in the library. To make that cleaner, you'd have to use a context provider.

**Comment by warren-bank** [comment]
I guess that boils down to person preference.. or maybe a trade-off between pragmatism vs. strict adherence to a particular pattern.

Drilling down on what you said about coupling components to a global state. Please correct me if I'm wrong, but isn't that analogous what the `react-redux` library does? They use a wrapper component that translates mutations to the global Redux store into updated props passed to a child component.. forcing it to re-render. This approach doesn't tie directly into the Redux store but, rather, allows a global dispatcher to send messages directly to React components (no wrapper necessary).. and each React component can choose how to update its state (if at all).. and any change in state would trigger the effected component to re-render.

One of the things that I love about Redux is that you can dispatch an action from anywhere.. and any reducer that cares to act on it is free to do so. This follows a similar approach: register a dispatcher.. be notified of all actions.. use them to mutate component state as you like.

I don't see any harm in passing actions to all React dispatchers.. when their corresponding reducers will safely ignore all action types but the few they choose to care about (ie: by returning the original unmodified state).

Plus, in the spirit of why React hooks are awesome, I would opt to avoid adding more components to the tree than is absolutely necessary.

Off-hand.. I have a hard time trying to think of a scenario where I would want to mix Redux state with React state, but life happens.. and sometimes you need to be flexible.

Unless there is a legitimate technical reason that would break how components render, or negatively impact performance optimizations that are in place.. then as I said earlier, I think it's only a matter of personal preference. If this pattern appeals.. cool, use it. If it feels wrong.. cool, don't use it :)

**Comment by ianobermiller** [comment]
Yup, I can see the utility in this. Nice work making your idea a reality
that others can share!
