### ISSUE TITLE
ts error in example

### ISSUE THREAD

**Issue by fuleinist** [facebookincubator/redux-react-hook#79]
TSlint is throwing error at line[36, 60] ./example/src/Store.ts per below

'Untyped function calls may not accept type arguments.ts(2347)'

Should this already resolved by the following commit?
https://github.com/facebookincubator/redux-react-hook/commit/d68d7a1df3fb1e00c96ba3a8d9cd3ebb557184aa

**Comment by ianobermiller** [comment]
Did you build the main directory first? It copies some files into the example directory. We should probably just get rid of TSLint anyway at this point. Feel free to send a PR if you'd like to help!

**Comment by ianobermiller** [comment]
I can't reproduce this (and TS shows the call is typed correctly). I'm not even using TSLint for this repo (not in package.json). Try disabling TSLint for this workspace?
