### ISSUE TITLE
another crazy thought: reimplementation of Redux reselect.. built on top of this library

### ISSUE THREAD

**Issue by warren-bank** [facebookincubator/redux-react-hook#80]
Hi.. it's me again :)

This issue is unrelated to my previous [issue #78](https://github.com/facebookincubator/redux-react-hook/issues/78).. where I introduced a [little library](https://github.com/warren-bank/react-custom-hooks/tree/master/packages/unified-redux-react-hook) that is a light-weight wrapper around the `redux-react-hook` library to add an enhancement to `useDispatch()`.

This issue pertains to another enhancement that I added to [that library](https://github.com/warren-bank/react-custom-hooks/tree/master/packages/unified-redux-react-hook), which is a function called `createReduxSelector` which aims to provide a (very nearly) drop-in replacement for [Redux reselect](https://github.com/reduxjs/reselect#api).

Links to learn more..
* [README](https://github.com/warren-bank/react-custom-hooks/tree/master/packages/unified-redux-react-hook#user-content-api-create-redux-selector)
* [source code](https://github.com/warren-bank/react-custom-hooks/blob/unified-redux-react-hook/v01.00.09/packages/unified-redux-react-hook/hook/unified-redux-react-hook.js#L63)
* unit tests:
  - [source code](https://github.com/warren-bank/react-custom-hooks/blob/unified-redux-react-hook/v01.00.09/packages/unified-redux-react-hook/tests/spec/02.js)
  - [run in browser](https://warren-bank.github.io/react-custom-hooks/packages/unified-redux-react-hook/tests/mocha.html)

I just wanted to let you know about it..
* it's already extremely efficient
  - there's always room for improvement, and I'm very open to ideas/suggestions
* is this something you'd consider including in the upstream `redux-react-hook` library?

**Comment by warren-bank** [comment]
If you don't mind me picking your brain.. I'm on the fence about one topic that may have a slight impact on efficiency.. and I'm curious your thoughts.

Boiling the scenario down as much as possible.. here is the situation:
* there are a whole bunch of `useMappedState` functions
* when the component is forced to update, the output of all of these functions are used to calculate a new value

If a custom equality function (ex: shallow, deep, etc) was to be introduced to improve efficiency, would it be better to:

1. apply it to `useMappedState`.. to prevent the component from re-rendering unnecessarily
2. apply it to the result of the function that depends on all the `useMappedState` output.. to memoize this result
3. apply it to both (1) and (2)

- - - -

Specifically:

__in `useMappedState`:__

https://github.com/facebookincubator/redux-react-hook/blob/5275dffd8defce004afd6ea5de3c9e30a0f987a1/src/create.ts#L137-L139

- - - -

I'm debating changing the shape of the _options_ Object to maybe something like:

```javascript
equality: {
  forceUpdate: [],
  recalculate: ''
}
```

where:
* `options.equality.forceUpdate` contains an Array of strings (ex: 'shallow', 'deep', null) that is the same length and order as the input-selectors in the input parameters
  - each value determines the custom equality function passed to the corresponding `useMappedState`
* `options.equality.recalculate` is a string (ex: 'shallow', 'deep', null)
  - this value determines how the result of the function that depends on all the `useMappedState` output is memoized

shortcuts:
* `if (typeof options.equality === 'string')`
  - `options.equality = {forceUpdate: [], recalculate: options.equality}`
* `if (typeof options.equality.forceUpdate === 'string')`
  - `options.equality.forceUpdate = inputSelectors.map(() => options.equality.forceUpdate)`

but.. I'm not entirely sure if this is the best strategy

any thoughts?

**Comment by warren-bank** [comment]
update: I just made the proposed change. Ultimately, the default behavior is the unchanged. This just adds the ability to precisely configure all of the equality functions.. to fine tune (a) when Redux state change should trigger the React component to re-render, and (b) how the Redux selector is memoized. ..Always good to have knobs and levers for when you need them.

**Comment by ianobermiller** [comment]
That looks interesting, I'm having a bit of trouble following what it is for, though. I see a lot of [hooks being called conditionally](https://github.com/warren-bank/react-custom-hooks/blob/master/packages/unified-redux-react-hook/hook/unified-redux-react-hook.js#L158-L160) which is usually not good, but if it is the same on every call it might be fine. What does this library buy you over just using `reselect` directly?

I'd like to keep this library (redux-react-hook) lean, so this should be a separate module. I'm going to close this issue, but we can have further discussion here.

**Comment by warren-bank** [comment]
I totally agree with your concern about hooks being called in conditional blocks. While this appears to violate the 1st rule of hooks, this particular usage is safe under the implied contract that:
* the __number__ _and_ __type__ of arguments passed to `createReduxSelector(..args)` is _always_ the same every time the React component renders

As for my motivation to experiment with a re-implementation of this library:
* it serves a very important purpose
  - memoizing a (potentially costly) function that depends on values either directly obtained from _or_ indirectly derived from the Redux store
* it does _not_:
  - subscribe to the Redux store to listen for updates to the global state
  - integrate with React components
    * ex: to force a render update when the value of the memoized result changes

Since the purpose of this library is to provide good integration between Redux and React, these 2 missing ingredients (taken together) felt like a good candidate for inclusion. The `useMappedState()` method provides a very easy path to do so, since it already does most of the heavy lifting.

* provided by `useMappedState()`:
  - it subscribes to the Redux store to listen for updates to the global state
  - it forces a render update when the value of the memoized result changes
* strategy to utilize this method:
  - pass each input-selector to `useMappedState()`
    * the equality function can be configured for each
    * when equality returns `false`:
      - `useMappedState()` is going to force a render update
      - the "costly" function is going to receive new input, which causes memoization to update and the function to run

**Comment by warren-bank** [comment]
To be entirely honest, I only glanced at the [recommended methodology](https://github.com/facebookincubator/redux-react-hook#how-can-i-use-a-selector-creator-like-in-reselect) because it strikes me as very overly complicated.

If that methodology is feasible, then I would challenge you to fork [example # 4](https://codesandbox.io/s/dawn-mountain-b562n) and rewrite it (using only `redux-react-hook`) to produce the same output. I'm honestly curious what that solution would look like :)
