### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Gentlemancj** [facebookincubator/redux-react-hook#85]
the little change will make global render(update all component who used useMappedState function)

![image](https://user-images.githubusercontent.com/22905283/77253194-bcb21080-6c93-11ea-9d95-47de56380c50.png)

**Comment by ianobermiller** [comment]
Sorry, I'm not sure I understand. Are you proposing a change to the docs? Can you send it as a PR instead, or provide me the before and after?

**Comment by ianobermiller** [comment]
I'm going to close this issue for now, but please comment if you have more info and I can reopen!
