### ISSUE TITLE
Would it be possible to use redux-form with StoreContext.Provider from redux-react-hook?

### ISSUE THREAD

**Issue by sainiankit** [facebookincubator/redux-react-hook#87]
The following code results in: **_Invariant Violation: Could not find "store" in the context of "Connect(t)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(t) in connect options._**

```
import {StoreContext} from 'redux-react-hook';
.
.
<StoreContext.Provider value={store}>
    <ReduxFormComponent />
</StoreContext.Provider>
```
However, this works fine. 
```
import { Provider } from 'react-redux';
import {StoreContext} from 'redux-react-hook';
.
.
const store = useContext(StoreContext);
        
<Provider store={store}>
    <ReduxFormComponent />
</Provider>
```

`redux-form` seems to depend on `react-redux`'s Provider. What would be the best way around this?

**Comment by ianobermiller** [comment]
If you want to use both `react-redux` and `redux-react-hook`, you need both of their providers.
