### ISSUE TITLE
[need help] Does it support aysnc reducer?

### ISSUE THREAD

**Issue by Sara2009** [facebookincubator/redux-react-hook#96]
The [exapmle](https://codesandbox.io/s/github/ianobermiller/redux-react-hook-example) shows the synchronously reducer.  It returns the state directly. I wonder how to write an async reducer.

**Comment by ianobermiller** [comment]
This question isn't really specific to `redux-react-hook`. The Redux docs have a good section on [async actions](https://redux.js.org/tutorials/fundamentals/part-6-async-logic).
